sudo: required
dist: trusty

language: node_js
node_js:
  - '4.5'

install:
  - cd angular1
  - sh install.sh

script:
  - sh test.sh

after_success:
  - cd ..
  - bash deploy.sh angular1

branches:
  except:
    - gh-pages

