sudo: required
dist: trusty

language: node_js
node_js:
  - '4'

install:
  - cd angular1
  - sh install.sh

script:
  - sh test.sh

after_success:
  - cd ..
  - bash deploy.sh angular1

branches:
  only:
    - gh-pages     # test the gh-pages branch
    - /(.*)/       # test every other branch
