sudo: required
dist: trusty

language: node_js
node_js:
  - '4.5'

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - npm install

script:
  - npm run test-single-run
  - (npm start > /dev/null &) && (npm run protractor)

after_success:
- bash deploy.sh

# Travis needs the token to push to github gh-pages
env:
  global:
    secure: YkfVJwqX01gHKtCxTYi1wvHRAdHYvolUAO6bHfqc5HRzLKFh+xygDLez6fws+BufqDphWBjK5TKdL/HJMWyDB2MxglPcrKkdH7ZTVBXQwldRlGIGkCOlsFXyask7/XTlGP3SWPRiZFJmKI4UNMHknNJuWaujSMs7seQ81fZugY3OyVkuBym/Ld0wKX8DedDj6qy+iEwlMkss8NvVndmr3CSbxqJwiPEWC/W7tx7rNbZ8/i3nGG6DNZmIgH4V+XgolhlrtjkWA0O+q6EaAiLfbNDGvbUZg5TRh37IIkAqA40A3IJHSPN9ayLZikGqlQEd675yyVIEi9AUNeQo0cDAVNeVocPVTZXGQscpb6RUx7Z9KbtCYsRSPvc4ZzVLucJhP/QaKqZK39JuSCt1OCiXZjWjZ/k/TXMw4eO+IuOIbroaGFBUF4Hm2X4xq1kA9k9FpR7QFY6PKWj41uf7tcr4xB0CzV/DHFLRpkEoMqboaBWPZBY7l9/u6eCZZLjs2j8f+uQe0r8kGxwIg5BnK5GX50DGUlJ4R34bkt5gj9fsqta0QpZBWh/0/oXd4tL5qxfppXkONMRyfhpLPDm6vtDpw0aWEh/6D/Mjii2G+YyhUA7ThlWC+/roEB1kABlM/f3YnB8EGcPQlLaANhkJjPX9t4XvdAcEBJB/kNse8/vZd60=

