sudo: required
dist: trusty

language: node_js
node_js:
  - '4.5'

install:
  - echo 'do nothing'

script:
  - echo 'do nothing...'

branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /(.*)/       # test every other branch
